services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Danilovl\PermissionMiddlewareBundle\EventListener\ControllerListener:
    arguments:
      $container: '@service_container'
      $environment: '%kernel.environment%'

  Danilovl\PermissionMiddlewareBundle\EventListener\ResponseListener:
    arguments:
      $container: '@service_container'
      $environment: '%kernel.environment%'
