services:
  danilovl.listener.permission_middleware:
    class: Danilovl\PermissionMiddlewareBundle\EventListener\PermissionListener
    public: false
    autowire: true
    tags:
      - { name: kernel.event_listener, event: kernel.controller, method: onKernelController}
